### ISSUE TITLE
Attempt to access websocket outside of a relevant context

### ISSUE THREAD

**Issue by SmartManoj** [erdewit/nest_asyncio#10]
```
RuntimeError: Attempt to access websocket outside of a relevant context
Attempt to access websocket outside of a relevant context
Traceback (most recent call last):
  File "D:\SmartBot\my_env\SmartBot\telegram.py", line 888, in wa2tg2
    data = await websocket.receive()
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\local.py", line 115, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\local.py", line 84, in _get_current_object
    return object.__getattribute__(self, '__LocalProxy_local')()
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\globals.py", line 14, in _ctx_lookup
    raise RuntimeError(f"Attempt to access {name} outside of a relevant context")

```
In quart and telethon

**Comment by erdewit** [comment]
The problem is that nest_asyncio has to copy the context and that quart then doesn't recognize this copy.
The context copying is necessary to make recursive calling possible (by default ``context.run`` does not allow this).

I think there's not much I can do about it.
