### ISSUE TITLE
KeyError at del curr_tasks[loop] in leave_task

### ISSUE THREAD

**Issue by bggardner** [erdewit/nest_asyncio#26]
During high frequency calls in an implementation awaiting `websockets.recv()`, I occasionally receive:
```
Exception in callback Task.__wakeup(<Future finished result=None>)
handle: <Handle Task.__wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 150, in run
    ctx.run(self._callback, *self._args)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 303, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 108, in step
    step_orig(task, exc)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 287, in __step
    _leave_task(self._loop, self)
  File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 122, in leave_task
    del curr_tasks[loop]
KeyError: <_UnixSelectorEventLoop running=False closed=False debug=False>
```

**Comment by erdewit** [comment]
This should be fixed with version 1.4.0
