### ISSUE TITLE
Collision with AsyncIO

### ISSUE THREAD

**Issue by doyled-it** [erdewit/nest_asyncio#89]
See [this comment](https://github.com/deedy5/duckduckgo_search/issues/185#issuecomment-1947324256). For whatever reason, when I install `duckduckgo_search` (which uses `nest_asyncio`), and try to run gradio, it returns with:

Script:

```python
import duckduckgo_search
import gradio as gr


def predict(message: str, history: list[str]) -> str:
    return "hello"


gr.ChatInterface(predict).launch()
```

Output:

```shell
Exception in thread Thread-4 (run):
Traceback (most recent call last):
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/site-packages/nest_asyncio.py", line 26, in run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/site-packages/nest_asyncio.py", line 40, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mdoyle/miniconda3/envs/ma/lib/python3.12/asyncio/events.py", line 698, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4 (run)'.

**Comment by erdewit** [comment]
In the recent versions of nest_asyncio a patched loop is automatically created when none exits in a thread, which should fix the issue.
